In [1]:
import numpy as np
import pandas as pd
pd.set_option("display.max_rows",None)
pd.set_option("display.max_columns",None)


In [2]:
a=pd.read_csv("Credit.csv")

In [3]:
a.head()

Loan_ID Gender Married  Dependents     Education Self_Employed  \
0  LP001002   Male      No         0.0      Graduate            No   
1  LP001003   Male     Yes         1.0      Graduate            No   
2  LP001005   Male     Yes         0.0      Graduate           Yes   
3  LP001006   Male     Yes         0.0  Not Graduate            No   
4  LP001008   Male      No         0.0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [5]:
a.shape

(981, 13)

In [6]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 981 entries, 0 to 980
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            981 non-null    object 
 1   Gender             957 non-null    object 
 2   Married            978 non-null    object 
 3   Dependents         956 non-null    float64
 4   Education          981 non-null    object 
 5   Self_Employed      926 non-null    object 
 6   ApplicantIncome    981 non-null    int64  
 7   CoapplicantIncome  981 non-null    float64
 8   LoanAmount         954 non-null    float64
 9   Loan_Amount_Term   961 non-null    float64
 10  Credit_History     902 non-null    float64
 11  Property_Area      981 non-null    object 
 12  Loan_Status        981 non-null    object 
dtypes: float64(5), int64(1), object(7)
memory usage: 99.8+ KB


In [7]:
a.isnull().sum()

Loan_ID               0
Gender               24
Married               3
Dependents           25
Education             0
Self_Employed        55
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           27
Loan_Amount_Term     20
Credit_History       79
Property_Area         0
Loan_Status           0
dtype: int64

In [9]:
a.isnull().sum()[a.isnull().sum()*100/a.shape[0]>40]

Series([], dtype: int64)

In [10]:
a=a.drop("Loan_ID",axis=1)

In [11]:
a.Gender=a.Gender.fillna("Male")
a.Married=a.Married.fillna("No")
a.Dependents=a.Dependents.fillna(0)
a.Self_Employed=a.Self_Employed.fillna("Yes")
a.LoanAmount=a.LoanAmount.fillna(a.LoanAmount.mean())
a.Loan_Amount_Term=a.Loan_Amount_Term.fillna(a.Loan_Amount_Term.mean())
a.Credit_History=a.Credit_History.fillna(0)
a.Loan_Status=a.Loan_Status.replace({"Y":1,"N":0})

In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
a[a.select_dtypes(include=["object"]).columns]=a[a.select_dtypes(include=["object"]).columns].apply(le.fit_transform)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test=train_test_split(a,test_size=0.2)

In [14]:
a_train_x=x_train.iloc[:,:-1]
a_train_y=x_train.iloc[:,-1]


In [15]:
a_test_x=x_test.iloc[:,:-1]
a_test_y=x_test.iloc[:,-1]


In [17]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()
dtree.fit(a_train_x,a_train_y)

DecisionTreeClassifier()

In [19]:
pred=dtree.predict(a_test_x)
pred

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1],
      dtype=int64)

In [21]:
from sklearn.metrics import confusion_matrix
confusion_matrix(a_test_y,pred)

array([[ 25,  21],
       [ 32, 119]], dtype=int64)

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(a_test_y,pred)

0.7309644670050761

In [25]:
# Feature Selection(Target var not included)
dtree.feature_importances_

array([0.00914524, 0.01090549, 0.04930665, 0.01869481, 0.01532978,
       0.23266481, 0.08920038, 0.21054672, 0.05806698, 0.28062001,
       0.02551912])

In [27]:
dtree.feature_importances_.sum()

0.9999999999999998

In [28]:
#Higher the value of feature importance more significant the variable is 
a_train_x.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [31]:
feature_imp=pd.DataFrame({"Features":a_train_x.columns,"importance":dtree.feature_importances_})

In [32]:
feature_imp

Features  importance
0              Gender    0.009145
1             Married    0.010905
2          Dependents    0.049307
3           Education    0.018695
4       Self_Employed    0.015330
5     ApplicantIncome    0.232665
6   CoapplicantIncome    0.089200
7          LoanAmount    0.210547
8    Loan_Amount_Term    0.058067
9      Credit_History    0.280620
10      Property_Area    0.025519

In [34]:
feature_imp.sort_values("importance",ascending=False)

Features  importance
9      Credit_History    0.280620
5     ApplicantIncome    0.232665
7          LoanAmount    0.210547
6   CoapplicantIncome    0.089200
8    Loan_Amount_Term    0.058067
2          Dependents    0.049307
10      Property_Area    0.025519
3           Education    0.018695
4       Self_Employed    0.015330
1             Married    0.010905
0              Gender    0.009145

In [35]:
a_train,a_test=train_test_split(a,test_size=0.2)

In [36]:
a_train_x=a_train.iloc[:,[9,5,7,6,8,2,10]]
a_train_y=a_train.iloc[:,-1]

In [37]:
a_test_x=a_test.iloc[:,[9,5,7,6,8,2,10]]
a_test_y=a_test.iloc[:,-1]

In [43]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()

In [44]:
dtree.fit(a_train_x,a_train_y)

DecisionTreeClassifier()

In [46]:
from sklearn.model_selection import GridSearchCV
search={"criterion":["gini","entropy"],
        "max_depth":(5,6,7,8),
        "min_samples_split":(20,40,50)}


In [47]:
grid=GridSearchCV(dtree,param_grid=search)
grid.fit(a_train_x,a_train_y)

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': (5, 6, 7, 8),
                         'min_samples_split': (20, 40, 50)})

In [48]:
grid.best_params_

{'criterion': 'gini', 'max_depth': 6, 'min_samples_split': 50}

In [49]:
dtree=DecisionTreeClassifier(criterion= 'gini', max_depth= 6, min_samples_split= 50)
dtree.fit(a_train_x,a_train_y)

DecisionTreeClassifier(max_depth=6, min_samples_split=50)

In [50]:
pred=dtree.predict(a_test_x)
pred

array([1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1],
      dtype=int64)

In [51]:
from sklearn.metrics import confusion_matrix
confusion_matrix(a_test_y,pred)

array([[ 30,  18],
       [ 15, 134]], dtype=int64)

In [52]:
from sklearn.metrics import accuracy_score
accuracy_score(a_test_y,pred)

0.8324873096446701