In [34]:
import pandas as pd
import numpy as np
pd.set_option("display.max_rows",None)
pd.set_option("display.max_columns",None)

In [35]:
a=pd.read_csv("CTG.csv")

In [36]:
a.head()

LB     AC   FM  NSP
0  120  0.000  0.0    2
1  132  0.006  0.0    1
2  133  0.003  0.0    1
3  134  0.003  0.0    1
4  132  0.007  0.0    1

In [37]:
a.shape

(2126, 4)

In [38]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2126 entries, 0 to 2125
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   LB      2126 non-null   int64  
 1   AC      2126 non-null   float64
 2   FM      2126 non-null   float64
 3   NSP     2126 non-null   int64  
dtypes: float64(2), int64(2)
memory usage: 66.6 KB


In [39]:
a.isnull().sum()

LB     0
AC     0
FM     0
NSP    0
dtype: int64

In [40]:
from sklearn.model_selection import train_test_split
a_test,a_train=train_test_split(a,test_size=0.2)


In [41]:
# Oversampling
a1=a_train[a_train.NSP==2]
a2=a_train[a_train.NSP==3]

In [42]:
a.shape

(2126, 4)

In [43]:
a_train=pd.concat([a_train,a1,a1,a2,a2,a2])

In [44]:
a_train.NSP.value_counts()

1    318
2    213
3    148
Name: NSP, dtype: int64

In [45]:
a_train_x=a_train.iloc[:,:-1]
a_train_y=a_train.iloc[:,-1]

In [46]:
a_test_x=a_test.iloc[:,:-1]
a_test_y=a_test.iloc[:,-1]

In [47]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()
dtree.fit(a_train_x,a_train_y)

DecisionTreeClassifier()

In [48]:
pred=dtree.predict(a_test_x)
pred

array([1, 1, 1, ..., 3, 3, 2], dtype=int64)

In [49]:
from sklearn.metrics import confusion_matrix
confusion_matrix(a_test_y,pred)

array([[1074,  138,  125],
       [  70,  116,   38],
       [  34,   32,   73]], dtype=int64)

In [50]:
from sklearn.metrics import accuracy_score
accuracy_score(a_test_y,pred)

0.7429411764705882

In [51]:
dtree.feature_importances_

array([0.49041327, 0.22935808, 0.28022865])

In [52]:
dtree.feature_importances_.sum()

1.0

In [53]:
feature_imp=pd.DataFrame({"Features":a_train_x.columns,"importance":dtree.feature_importances_})

In [54]:
feature_imp

Features  importance
0       LB    0.490413
1       AC    0.229358
2       FM    0.280229

In [24]:
a_train,a_test=train_test_split(a,test_size=0.2)

In [26]:
a_train_x=a_train.iloc[:,[0,1,2]]
a_train_y=a_train.iloc[:,-1]

In [28]:
a_test_x=a_test.iloc[:,[0,1,2]]
a_test_y=a_test.iloc[:,-1]

In [29]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier(criterion='entropy',max_depth=7,min_samples_split=40,class_weight="balanced")

In [30]:
dtree.fit(a_train_x,a_train_y)

DecisionTreeClassifier(class_weight='balanced', criterion='entropy',
                       max_depth=7, min_samples_split=40)

In [31]:
pred=dtree.predict(a_test_x)
pred

array([2, 3, 1, 3, 1, 2, 1, 1, 1, 1, 1, 1, 1, 3, 1, 2, 2, 2, 1, 1, 1, 1,
       3, 3, 1, 2, 2, 1, 2, 3, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 3, 1,
       1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 2,
       1, 1, 1, 2, 1, 1, 2, 3, 1, 1, 2, 3, 2, 1, 2, 1, 1, 2, 1, 2, 2, 1,
       1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 1, 3, 1, 3, 1, 1, 1, 3, 1,
       3, 3, 1, 2, 3, 1, 1, 2, 1, 3, 2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 3,
       1, 1, 2, 2, 1, 1, 1, 1, 3, 1, 2, 1, 2, 3, 1, 1, 2, 2, 1, 2, 2, 1,
       1, 3, 3, 1, 3, 3, 1, 1, 3, 1, 1, 2, 1, 2, 1, 1, 3, 2, 1, 3, 3, 3,
       3, 1, 3, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 2, 3, 2, 2, 3, 3, 1, 1, 3, 2, 1, 2, 1, 1, 3,
       3, 1, 1, 1, 2, 3, 1, 1, 3, 1, 1, 1, 2, 1, 1, 2, 3, 2, 1, 2, 1, 2,
       1, 1, 2, 3, 1, 2, 1, 3, 1, 1, 1, 1, 1, 3, 3, 2, 1, 1, 1, 1, 3, 3,
       1, 1, 1, 1, 1, 3, 2, 2, 2, 1, 3, 1, 2, 1, 1, 3, 1, 1, 1, 2, 1, 1,
       3, 3, 1, 1, 1, 1, 3, 2, 2, 2, 1, 1, 1, 1, 3,

In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(a_test_y,pred)

array([[237,  58,  42],
       [  4,  46,   8],
       [  2,   5,  24]], dtype=int64)

In [33]:
from sklearn.metrics import accuracy_score
accuracy_score(a_test_y,pred)

0.7206572769953051

In [67]:
from sklearn.ensemble import RandomForestClassifier
ran=RandomForestClassifier(n_estimators=50,criterion="entropy")
ran.fit(a_train_x,a_train_y)

RandomForestClassifier(criterion='entropy', n_estimators=50)

In [68]:
pred=ran.predict(a_test_x)

In [69]:
pred

array([1, 1, 1, ..., 3, 3, 2], dtype=int64)

In [70]:
tab=confusion_matrix(a_test_y,pred)

In [71]:
tab

array([[1079,  145,  113],
       [  62,  132,   30],
       [  35,   26,   78]], dtype=int64)

In [72]:
accuracy_score(a_test_y,pred)

0.758235294117647